# Generated by Django 5.1.3 on 2024-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='cluster_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
